[package]
name = "sparse_graph"
version = "0.1.0"
authors = ["Tim Leslie"]
edition = "2018"
description = "Sparse graph algorithms"
licence = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
